name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Pull Vercel environment variables
        run: vercel pull --yes --environment=preview --token ${{ secrets.VERCEL_TOKEN }}

      - name: Build artifacts
        run: vercel build --token ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: vercel --prebuilt --token ${{ secrets.VERCEL_TOKEN }}